export const {
  REACT_APP_GAPI_CLIENT_ID: GAPI_CLIENT_ID,
  REACT_APP_WORDS_DOC_ID: WORDS_DOC_ID,
  REACT_APP_PHRASAL_VERBS_DOC_ID: PHRASAL_VERBS_DOC_ID,
  REACT_APP_IDIOMS_DOC_ID: IDIOMS_DOC_ID,
} = process.env;
